repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        name: ruff check
        args: [--fix]
      - id: ruff-format
        name: ruff format

  - repo: local
    hooks:
      - id: basedpyright
        name: basedpyright type check
        entry: uv run basedpyright
        language: system
        types: [python]
        pass_filenames: false